### PR TITLE
Merge rpc-maas into rpc-extras/rpc-maas

### PR DESCRIPTION
**Pull request by nrb**
This pull request merges the rpc-maas repo into the rpc-extras repo under an `rpc-maas` directory.

This was done to simplify product deployment scenarios, allowing the deployer to clone one repository and have all of the Rackspace things.

This approach retains the commit history of the rpc-maas files, in case it is needed.

The rpc-maas tags were *not* brought over with this merge; only the HEAD of master.

### CODE REVIEW

**Comment by stevelle** [comment]
does my :+1: even count on this?

**Comment by prometheanfire** [comment]
this pr still valid with the osad-mass-integration branch?

**Comment by stevelle** [comment]
it would make a rebase of the that branch smaller and easier to review which would be a good thing.

**Comment by prometheanfire** [comment]
we can do it piecemeal, doesn't mater much to me

**Comment by prometheanfire** [comment]
:+1:

**Comment by prometheanfire** [comment]
:-1:

**Pull request closed without merging**
