### PR TITLE
[WIP] Use virtualenv for maas plugins

### PR DESCRIPTION
**Pull request by mattt416**
This change implements the following two changes:

- maas plugins now use a .venv so there are no conflicts with packages
  installed on the hosts
- creates proper pip package variable names in rpc_maas role so that
  repo-builder.yml will include these packages when building repo
  packages

Closes issue #144

### CODE REVIEW

**Comment by prometheanfire** [comment]
why can repo-builder not build it?

**Comment by cloudnull** [comment]
@prometheanfire - the repo builder looks for lists with "*_pip_packages:" which is why the original package list was skipped.

@mattt416 - :+1: LGTM

**Comment by mattt416** [comment]
Hold off on merging -- going to see if I can use a venv here.

**Comment by mattt416** [comment]
@git-harry pointed out that this doesn't work, need to rethink or revert to original commit (not involving virtualenvs).

**Comment by mattt416** [comment]
Actually this does appear to be working, but needs more testing.  Appreciate any feedback.

**Comment by prometheanfire** [comment]
:+1: lgtm

**Pull request closed without merging**
