### PR TITLE
Add kernel modules, tuning and support packages for hosts

### PR DESCRIPTION
**Pull request by odyssey4me**
This patch adds several packages requested by RPC support to all hosts and
containers, adds kernel module loading and sysctl tuning to all hosts.

The reference for all additions can be found in the description and comments
for https://bugs.launchpad.net/openstack-ansible/+bug/1400424

### CODE REVIEW

**Comment by hughsaunders** [comment]
LGTM :+1:  
One question.. why debootstrap?

**Comment by odyssey4me** [comment]
@hughsaunders I have no idea, it was requested in the launchpad bug... ultimately I think the main purpose here is to provide the facility to do these things. This allows support to override if need be.

**Comment by hughsaunders** [comment]
Yep, lets get this merged :+1:

**Comment by mattt416** [comment]
There is a lot of duplication here w/ what's already defaulted in https://github.com/stackforge/os-ansible-deployment/blob/master/playbooks/roles/openstack_hosts/defaults/main.yml.

**Comment by rackertom** [comment]
debootstrap shouldn't be needed since we're presumably not building images. But it may have been pulled in as a dependency for one of the other packages. I suspect the reason for installing these outside of ansible plays may be chicken-and-the-egg situation where some level of configuration is required before ansible is run, but ansible is clearly the best tool to perform the install.

Either way. :+1: from me.

**Comment by hughsaunders** [comment]
@mattt416 I guess that duplication is so support can tune and add packages without adding them to OSAD

**Comment by odyssey4me** [comment]
@nrb The PR is https://github.com/rcbops/rpc-openstack/pull/81

**Comment by nrb** [comment]
@odyssey4me Thanks. Does anyone know of a reason that this shouldn't be backported to Kilo? @hughsaunders @mattt416 @rackertom

**Pull request merged**
