### PR TITLE
Osad upgrade integration kilo

### PR DESCRIPTION
**Pull request by stevelle**
Backport of https://github.com/rcbops/rpc-extras/pull/131

### CODE REVIEW

**Comment by prometheanfire** [comment]
:+1:

**Comment by sigmavirus24** [comment]
Looks good and like a straightforward backport. :+1:

**Comment by stevelle** [comment]
This will not work until we update the submodule after https://review.openstack.org/#/c/187294/ merges.
Other fixes may be necessary pending review of https://github.com/rcbops/rpc-extras/pull/131

**Comment by odyssey4me** [comment]
:-1: until such time that the issues identified in https://github.com/rcbops/rpc-extras/pull/131 are addressed

**Comment by stevelle** [comment]
superseded by #141

**Pull request closed without merging**
